сделала заготовку для BigCard
dev-courses/remontina pull request #1
Opened 2021-05-23 11:40 UTC by susazybka

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/home_screen.dart
> +        padding: EdgeInsets.symmetric(horizontal: 15.0, vertical: 15.0),
1) Здесь ширина и высота не отличаются, поэтому разумно использовать EdgeInsets.all()
2) Скорее всего отступ будет одинаковым на всех экранах, поэтому имеет смысл вынести 15 в константу.

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +
Ещё нужен параметр `final VoidCallback? onTap`, в который будет передаваться метод, который должен вызываться при нажатии на карточку.

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +                ),
Вот такие маленькие компоненты лучше делать в одну строку, чтоб не рассеивать внимание. Хотя это и вкусовщина, конечно.
`SizedBox(height: 12.0),`

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +                      fontStyle: FontStyle.normal),
```suggestion
                      fontStyle: FontStyle.normal,
                    ),
```

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +                      fontStyle: FontStyle.normal),
```suggestion
                      fontStyle: FontStyle.normal,
                     ),
```

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +                      fontStyle: FontStyle.normal),
А вообще, писать `fontStyle: FontStyle.normal` и `fontWeight: FontWeight.normal` здесь не имеет смысла, т.к. по-умолчанию оно и так имеет такое значение.

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +            Image.asset(
Нет отступа между картинкой и текстом

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +            )
```suggestion
            ),
```

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +                      fontStyle: FontStyle.normal),
Здесь тоже не имеет смысла писать `fontStyle: FontStyle.normal`

2021-05-30 15:33 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +  @override
Вот здесь не помешает пустая строка, чтобы визуально отделить конструктор от остального кода. Да и в целом стоит перед каждым методом оставлять пустую строку.

2021-05-30 16:04 UTC, susazybka commented on lib/presentation/home/widgets/big_card.dart
> +
параметр я добавила, а как добавить метод?

2021-05-30 16:06 UTC, susazybka commented on lib/presentation/home/widgets/big_card.dart
> +                      fontStyle: FontStyle.normal),
потому что он по умолчанию?

2021-05-30 17:30 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +
Принцип такой же, как при работе с кнопками.
Т.е. в месте использования будет написано что-то типа:
```dart
BigCard(
  title: 'Title',
  description: 'Long long description',
  onTap: () {
    print('It is tapped!');
  },
),
```

2021-06-06 07:21 UTC, san-smith requested changes

2021-06-06 07:21 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +      padding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 10.0),
Если отступ одинаковый и по вертикали и по горизонтали, то почему бы не использовать `all`?

2021-06-06 07:21 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +        // border: Border.all(color: AppColors.borderBigCardGreen, width: 2.0),
Коммитить вот такие закомментированные куски кода - плохая идея.

2021-06-06 07:21 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +                      color: AppColors.textBigCardWhite),
```suggestion
                      color: AppColors.textBigCardWhite,
                    ),
```

2021-06-06 07:21 UTC, san-smith commented on lib/presentation/home/widgets/big_card.dart
> +          SizedBox(width: 10.0),
Этот отступ будет всегда, даже если картинки нет. А нам хотелось бы, чтобы отступ был только если есть картинка.

2021-06-08 15:13 UTC, merged